# Здесь хранятся данные всех созданных рудников, чтобы удалить рудник удалите полностью его данные
per_min_spawn: 60 #раз в сколько минут будет происходить спавн
world: world #название мира в котором будет спав руды
counterOfMines: 0  #это счетчик