name: MineKyas
version: '1.0'
main: org.kyas.spawnermine.MineKyas
api-version: '1.20'
authors: [Kyas17]
description: Create spawn dot of ore
commands:
  createDotMine:
    description: открывает меню создания точки спавна
    aliases:
      - cdm
    permission: spawnerMine.openGui
    permission-message: У вас нет прав создавать новые рудники!
    usage: /createDotMine [reload]